[[cells]]
name = "cellnames-always-success"
enable_type_id = true
location = { file = "contracts/always-success/target/riscv64imac-unknown-none-elf/release/cellnames-always-success" }

[lock]
code_hash = "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8"
args = "0xa776bf02d19cafa3749d906cc2c9ab1cf1e80ff7"
hash_type = "type"
